when:
  - event: [push, manual]

steps:
  - name: publish
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      repo: dta32/bandung-coffeeshop-fe
      dockerfile: Dockerfile
      platforms: linux/amd64
      tags: ${CI_COMMIT_SHA:0:7}
      cache_images:
        - dta32/bandung-coffeeshop-fe:cache
      build_args:
        VITE_API_BASE_URL: https://bdgcafe.com/api
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
