/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MeetInTheMiddleRouteImport } from './routes/meet-in-the-middle'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreIndexRouteImport } from './routes/explore.index'
import { Route as ExploreSplatRouteImport } from './routes/explore.$'
import { Route as CafeCafeIdRouteImport } from './routes/cafe.$cafeId'

const MeetInTheMiddleRoute = MeetInTheMiddleRouteImport.update({
  id: '/meet-in-the-middle',
  path: '/meet-in-the-middle',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreSplatRoute = ExploreSplatRouteImport.update({
  id: '/explore/$',
  path: '/explore/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CafeCafeIdRoute = CafeCafeIdRouteImport.update({
  id: '/cafe/$cafeId',
  path: '/cafe/$cafeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/meet-in-the-middle': typeof MeetInTheMiddleRoute
  '/cafe/$cafeId': typeof CafeCafeIdRoute
  '/explore/$': typeof ExploreSplatRoute
  '/explore/': typeof ExploreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/meet-in-the-middle': typeof MeetInTheMiddleRoute
  '/cafe/$cafeId': typeof CafeCafeIdRoute
  '/explore/$': typeof ExploreSplatRoute
  '/explore': typeof ExploreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/meet-in-the-middle': typeof MeetInTheMiddleRoute
  '/cafe/$cafeId': typeof CafeCafeIdRoute
  '/explore/$': typeof ExploreSplatRoute
  '/explore/': typeof ExploreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/meet-in-the-middle'
    | '/cafe/$cafeId'
    | '/explore/$'
    | '/explore/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/meet-in-the-middle'
    | '/cafe/$cafeId'
    | '/explore/$'
    | '/explore'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/meet-in-the-middle'
    | '/cafe/$cafeId'
    | '/explore/$'
    | '/explore/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MeetInTheMiddleRoute: typeof MeetInTheMiddleRoute
  CafeCafeIdRoute: typeof CafeCafeIdRoute
  ExploreSplatRoute: typeof ExploreSplatRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/meet-in-the-middle': {
      id: '/meet-in-the-middle'
      path: '/meet-in-the-middle'
      fullPath: '/meet-in-the-middle'
      preLoaderRoute: typeof MeetInTheMiddleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$': {
      id: '/explore/$'
      path: '/explore/$'
      fullPath: '/explore/$'
      preLoaderRoute: typeof ExploreSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cafe/$cafeId': {
      id: '/cafe/$cafeId'
      path: '/cafe/$cafeId'
      fullPath: '/cafe/$cafeId'
      preLoaderRoute: typeof CafeCafeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MeetInTheMiddleRoute: MeetInTheMiddleRoute,
  CafeCafeIdRoute: CafeCafeIdRoute,
  ExploreSplatRoute: ExploreSplatRoute,
  ExploreIndexRoute: ExploreIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
